version: "3"
services:
  mongo:
    image: "mongo:latest"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "27017:27017"
  redis:
    image: "redis:latest"
  node:
    ports:
      - "5000:5000"
    build:
      dockerfile: Dockerfile
      # context: ./
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_DB_NAME=Articledb
      - MONGO_PORT=27017
      - MONGO_HOST=mongo
      - PORT=5000
      - CONNECTIONSTRING=mongodb://mongo:27017/Articledb
    # links:
    #   - mongo
    #   - redis
    volumes:
      - ./:/code
volumes:
  mongodb:
  mongodb_config:

